variables:
  GIT_STRATEGY: fetch
  # BASE IMAGE (kind of the folder for all images)
  BASE_IMAGE: registry.gitlab.com/mathis1993/mood_diary_project

  # APPLICATION IMAGES
  APP_IMAGE: $BASE_IMAGE:django.$CI_COMMIT_REF_SLUG
  APP_TEST_IMAGE: $APP_IMAGE.test

stages:
  - build
#  - test
  # - release
  - deploy

build_mood_diary:
  stage: build
  # The runner defines a tag and will only pick up jobs with this tag
  tags:
    - shell  # runner with shell executor
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --tag $APP_TEST_IMAGE --target=staging .
    - docker push $APP_TEST_IMAGE

#test_mood_diary:
#  stage: test
#  image: $APP_TEST_IMAGE
#  tags:
#    - docker  # runner with docker executor
#  before_script:
#    - cd /app
#  script:
#    - pytest

deploy_to_staging:
    stage: deploy
    tags:
      - shell
    script:
      - cp infra/staging/docker-compose.yml ${DEPLOY_TARGET_DIR}/docker-compose.yml
      - cd ${DEPLOY_TARGET_DIR}
      - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker compose pull && docker compose up -d
#      - docker compose exec backend_django python manage.py create
    variables:
      DEPLOY_TARGET_DIR: /home/docker/mood_diary
