# pre-commit configuration that runs multiple tools for code quality before every commit
exclude: .*\/migrations\/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
      args: ["--allow-multiple-documents", "--unsafe"]
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: fix-encoding-pragma
      args: ["--remove"]  # we are a py3-only project

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ["--config=pyproject.toml"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--filter-files"]

  - repo: https://github.com/PyCQA/flake8.git
    rev: 3.8.1
    hooks:
      - id: flake8
        exclude: ".git .hg .idea venv __pycache__ */migrations/* config"
        args: ["--config=.flake8"]
        additional_dependencies: [flake8-bugbear]
