# docker-compose file for development where postgres and redis are run
# as services but the django app is run locally
version: '3.8'

services:
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.20-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./.docker/redis/data:/var/lib/redis/data
