# Configration file a python project
[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
force-exclude = """
/(
    .git
  | .hg
  | .eggs
  | .mypy_cache
  | .tox
  | .venv
  | .venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
"""

[tool.isort]
profile = "black"
line_length = 100
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
no_lines_before = "LOCALFOLDER"
skip_glob = ["*/migrations/*.py"]
src_paths = ["src", "."]
known_thirdparty = ["django"]

[tool.coverage.run]
omit = [
    "*/tests/*",
    "*/migrations/*",
    "*/prototypes/*",
    "*/site-packages/*",
    "*/test_*",
    "scripts/*",
    "docker/*",
    "config/*",
]

[tool.coverage.report]
precision = 2

[tool.pytest.ini_options]
python_files = "tests.py test_*.py *_tests.py"
DJANGO_SETTINGS_MODULE= "config.settings.test"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "jwt_scope: sets required scope for api test",
]
