ACTIVITIES_DE_EN = {
    "Schlaf/Sleep": {
        "Aufstehen": "Getting up",
        "Zu Bett gehen": "Going to bed",
        "Schlafen": "Sleeping",
        "Sonstiges": "Other",
    },
    "Essen/Food": {
        "Mahlzeit": "Meal",
        "Snack": "Snack",
        "Sonstiges": "Other",
        "Restaurant": "Restaurant",
    },
    "Studium/Studies": {
        "Vorlesung": "Lecture",
        "Seminar": "Seminar",
        "Lehrveranstaltung": "Course",
        "Lernen": "Studying",
        "Vor-/Nachbereitung": "Preparation/Review",
        "Arbeitsgruppe": "Study group",
        "Projektarbeit": "Project work",
        "Sonstiges": "Other",
    },
    "Arbeit/Work": {
        "Nebenjob": "Part-time job",
        "Ehrenamt": "Volunteer work",
        "Sonstiges": "Other",
    },
    "Soziales/Social": {
        "Freund*innen treffen": "Meeting friends",
        "Parter*in treffen": "Meeting partner",
        "Telekommunikation Freund*innen": "Telecommunication with friends",
        "Telekommunikation Parter*in": "Telecommunication with partner",
        "Familie treffen": "Meeting family",
        "Telekommunikation Familie": "Telecommunication with family",
        "Ausgehen/Party": "Going out/Partying",
        "Unterstützung Freund*innen": "Supporting friends",
        "Unterstützung Familie": "Supporting family",
        "Unterstützung Partner*in": "Supporting partner",
        "Sonstiges": "Other",
    },
    "Bewegung/Physical Activity": {
        "Sport": "Sports",
        "Spazieren": "Walking",
        "Wegstrecke Fuß/Rad": "Distance by foot/bike",
        "Sonstiges": "Other",
    },
    "Entspannung/Relaxation": {
        "Meditation": "Meditation",
        "Massage": "Massage",
        "Wellness": "Wellness",
        "Sauna": "Sauna",
        "Entspannungsübung": "Relaxation exercise",
        "Ruhe ohne Aktivität": "Rest without activity",
        "Sonstiges": "Other",
    },
    "Medien/Media": {
        "PC Gaming": "PC Gaming",
        "Surfen": "Browsing",
        "PC Sonstiges": "PC Other",
        "Handy Gaming": "Mobile Gaming",
        "Social Media": "Social Media",
        "Filme/Serien": "Movies/Series",
        "Videos": "Videos",
        "News": "News",
        "Handy Sonstiges": "Mobile Other",
        "Podcasts": "Podcasts",
        "Sonstiges": "Other",
    },
    "Erledigungen/Errands": {
        "Aufräumen/Putzen": "Cleaning/Tidying",
        "Einkaufen": "Shopping",
        "Kochen": "Cooking",
        "Wäsche": "Laundry",
        "Reparaturen": "Repairs",
        "Garten-/Balkonarbeit": "Gardening/Balcony work",
        "Versicherungen/Finanzen": "Insurance/Finances",
        "Arztbesuch": "Doctor's visit",
        "Therapie/Beratung": "Therapy/Counseling",
        "Sonstiges": "Other",
    },
    "Kultur und Kreatives/Culture and Creativity": {
        "Musik hören": "Listening to music",
        "Musik machen": "Making music",
        "Konzert": "Concert",
        "Malen/Zeichnen/Basteln": "Painting/Drawing/Crafting",
        "Museum/Ausstellung": "Museum/Exhibition",
        "Lesen": "Reading",
        "Event/Veranstaltung": "Event",
        "Handarbeit/-werken": "Handicrafts",
        "Einrichten/Dekorieren": "Decorating",
        "Sonstiges": "Other",
    },
    "Problemverhalten/Problematic Behavior": {
        "Grübeln": "Ruminating",
        "Sorgen": "Worrying",
        "Selbstverletzung": "Self-harm",
        "Alkohol-/Drogenkonsum": "Alcohol/Drug consumption",
        "Sonstiges Problemverhalten": "Other problematic behavior",
    },
    "Transport/Transportation": {
        "Auto fahren": "Driving in a car",
        "Zug fahren": "Taking the train",
        "Fliegen": "Flying",
        "Sonstiges": "Other",
    },
    "Zusätzliches/Other": {
        "Andere Aktivität": "Other activity",
    },
}
