# Generated by Django 4.2.2 on 2023-08-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['viewed', '-created_at']},
        ),
    ]
