# Generated by Django 4.2.2 on 2023-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_de',
            field=models.TextField(null=True),
        ),
    ]
