# Generated by Django 4.2.2 on 2023-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_message_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True),
        ),
    ]
