# Generated by Django 4.2.2 on 2023-08-04 07:46

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diaries_activities',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diaries_activity_categories',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diaries_emotions',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'diaries_moods',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='MoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_diary', to='clients.client')),
            ],
            options={
                'db_table': 'diaries_mood_diaries',
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'diaries_strains',
            },
        ),
        migrations.CreateModel(
            name='StrainArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diaries_strain_areas',
            },
        ),
        migrations.CreateModel(
            name='MoodDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mood_and_emotion_info', models.TextField(blank=True, default=None, null=True)),
                ('strain_info', models.TextField(blank=True, default=None, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mood_diary_entries', to='diaries.activity')),
                ('emotion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mood_diary_entries', to='diaries.emotion')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mood_diary_entries', to='diaries.mood')),
                ('mood_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diaries.mooddiary')),
                ('strain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mood_diary_entries', to='diaries.strain')),
                ('strain_area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mood_diary_entries', to='diaries.strainarea')),
            ],
            options={
                'db_table': 'diaries_mood_diary_entries',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='diaries.activitycategory'),
        ),
    ]
