# Generated by Django 4.2.2 on 2023-08-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['category__value', 'value']},
        ),
    ]
