# Generated by Django 4.2.2 on 2023-06-20 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooddiaryentry',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mooddiaryentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
