# Generated by Django 4.2.2 on 2023-06-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_require_mood_diary_entry_start_and_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['value']},
        ),
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['value']},
        ),
    ]
