# Generated by Django 4.2.2 on 2023-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_activity_value_de_activitycategory_value_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='label_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
