# Generated by Django 4.2.2 on 2023-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_alter_activity_and_mood_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooddiaryentry',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
