# Generated by Django 4.2.2 on 2023-08-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_english_translation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['category__value_de', 'value_de']},
        ),
    ]
