ACTIVITIES_DE = {
    "Schlaf": [
        "Aufstehen",
        "Zu Bett gehen",
        "Schlafen",
        "Sonstiges",
    ],
    "Essen": [
        "Mahlzeit",
        "Snack",
        "Sonstiges",
        "Restaurant",
    ],
    "Studium": [
        "Vorlesung",
        "Seminar",
        "Lehrveranstaltung",
        "Lernen",
        "Vor-/Nachbereitung",
        "Arbeitsgruppe",
        "Projektarbeit",
        "Sonstiges",
    ],
    "Arbeit": [
        "Nebenjob",
        "Ehrenamt",
        "Sonstiges",
    ],
    "Soziales": [
        "Freund*innen treffen",
        "Parter*in treffen",
        "Telekommunikation Freund*innen",
        "Telekommunikation Parter*in",
        "Familie treffen",
        "Telekommunikation Familie",
        "Ausgehen/Party",
        "Unterstützung Freund*innen",
        "Unterstützung Familie",
        "Unterstützung Partner*in",
        "Sonstiges",
    ],
    "Bewegung": [
        "Sport",
        "Spazieren",
        "Wegstrecke Fuß/Rad",
        "Sonstiges",
    ],
    "Entspannung": [
        "Meditation",
        "Massage",
        "Wellness",
        "Sauna",
        "Entspannungsübung",
        "Ruhe ohne Aktivität",
        "Sonstiges",
    ],
    "Medien": [
        "PC Gaming",
        "Surfen",
        "PC Sonstiges",
        "Handy Gaming",
        "Social Media",
        "Filme/Serien",
        "Videos",
        "News",
        "Handy Sonstiges",
        "Podcasts",
        "Sonstiges",
    ],
    "Erledigungen": [
        "Aufräumen/Putzen",
        "Einkaufen",
        "Kochen",
        "Wäsche",
        "Reparaturen",
        "Garten-/Balkonarbeit",
        "Versicherungen/Finanzen",
        "Arztbesuch",
        "Therapie/Beratung" "Sonstiges",
    ],
    "Kultur und Kreatives": [
        "Musik hören",
        "Musik machen",
        "Konzert",
        "Malen/Zeichnen/Basteln",
        "Museum/Ausstellung",
        "Lesen",
        "Event/Veranstaltung",
        "Handarbeit/-werken",
        "Einrichten/Dekorieren",
        "Sonstiges",
    ],
    "Problemverhalten": [
        "Grübeln",
        "Sorgen",
        "Selbstverletzung",
        "Alkohol-/Drogenkonsum",
        "Sonstiges Problemverhalten",
    ],
    "Transport": [
        "Auto fahren",
        "Zug fahren",
        "Fliegen",
        "Sonstiges",
    ],
    "Zusätzliches": [
        "Andere Aktivität",
    ],
}

ACTIVITIES_EN = {
    "Sleep": [
        "Getting up",
        "Going to bed",
        "Sleeping",
        "Other",
    ],
    "Food": [
        "Meal",
        "Snack",
        "Other",
        "Restaurant",
    ],
    "Study": [
        "Lecture",
        "Seminar",
        "Course",
        "Studying",
        "Preparation/Review",
        "Study group",
        "Project work",
        "Other",
    ],
    "Work": [
        "Part-time job",
        "Volunteer work",
        "Other",
    ],
    "Social": [
        "Meeting friends",
        "Meeting partner",
        "Telecommunication with friends",
        "Telecommunication with partner",
        "Meeting family",
        "Telecommunication with family",
        "Going out/Partying",
        "Supporting friends",
        "Supporting family",
        "Supporting partner",
        "Other",
    ],
    "Physical Activity": [
        "Sports",
        "Walking",
        "Distance by foot/bike",
        "Other",
    ],
    "Relaxation": [
        "Meditation",
        "Massage",
        "Wellness",
        "Sauna",
        "Relaxation exercise",
        "Rest without activity",
        "Other",
    ],
    "Media": [
        "PC Gaming",
        "Browsing",
        "PC Other",
        "Mobile Gaming",
        "Social Media",
        "Movies/Series",
        "Videos",
        "News",
        "Mobile Other",
        "Podcasts",
        "Other",
    ],
    "Errands": [
        "Cleaning/Tidying",
        "Shopping",
        "Cooking",
        "Laundry",
        "Repairs",
        "Gardening/Balcony work",
        "Insurance/Finances",
        "Doctor's visit",
        "Therapy/Counseling",
        "Other",
    ],
    "Culture and Creativity": [
        "Listening to music",
        "Making music",
        "Concert",
        "Painting/Drawing/Crafting",
        "Museum/Exhibition",
        "Reading",
        "Event",
        "Handicrafts",
        "Decorating",
        "Other",
    ],
    "Problematic Behavior": [
        "Ruminating",
        "Worrying",
        "Self-harm",
        "Alcohol/Drug consumption",
        "Other problematic behavior",
    ],
    "Transport": [
        "Driving in a car",
        "Taking the train",
        "Flying",
        "Other",
    ],
    "Additional": [
        "Other activity",
    ],
}
