# Generated by Django 4.2.2 on 2023-08-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('preconditions_description', models.TextField()),
                ('criterion', models.TextField(choices=[('threshold', 'Threshold'), ('change', 'Change')], max_length=255)),
                ('evaluation', models.TextField(choices=[('event-based', 'Event Based'), ('time-based', 'Time Based')], max_length=255)),
                ('conclusion_message', models.TextField()),
            ],
            options={
                'db_table': 'rules_rules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RuleTriggeredLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_triggered_logs', to='clients.client')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_logs', to='rules.rule')),
            ],
            options={
                'db_table': 'rules_triggered_logs',
            },
        ),
        migrations.CreateModel(
            name='RuleClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_users', to='clients.client')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rule_users', to='rules.rule')),
            ],
            options={
                'db_table': 'rules_rules_clients',
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='subscribed_clients',
            field=models.ManyToManyField(related_name='subscribed_rules', through='rules.RuleClient', to='clients.client'),
        ),
    ]
