# Generated by Django 4.2.2 on 2023-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_ruleclient_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleclient',
            options={'ordering': ['-active', 'rule__title']},
        ),
    ]
