# Generated by Django 4.2.2 on 2023-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_ruletriggeredlog_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='conclusion_message_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_de',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
