# Generated by Django 4.2.2 on 2023-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_rule_conclusion_message_de_rule_title_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='conclusion_message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
