# Generated by Django 4.2.2 on 2023-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_push_notifications_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_key_encrypted',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
