# docker-compose file for the staging environment where all components of the project
# are run as services (postgres, redis, django, celery consumer, celery scheduler).configs:
# Note that the staging system expects a traefik reverse proxy to be running on the host
# independently of this docker-compose file.
version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:15.2
    networks:
      - overlay
    env_file:
      - /home/docker/mood_diary/.env
    volumes:
      - /home/docker/mood_diary/postgres_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - overlay
    volumes:
      - /home/docker/mood_diary/redis/data:/var/lib/redis/data

  django:
    restart: always
    image: ${APP_TEST_IMAGE}
    networks:
      - overlay
      - web
    env_file:
      - /home/docker/mood_diary/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django-nginx.entrypoints=http"
      - "traefik.http.routers.django-nginx.priority=1"
      - "traefik.http.routers.django-nginx.rule=Host(`stage.mood-diary.de`)"
      - "traefik.http.routers.django-nginx.middlewares=traefik-https-redirect"
      - "traefik.http.routers.django-nginx-secure.entrypoints=https"
      - "traefik.http.routers.django-nginx-secure.priority=1"
      - "traefik.http.routers.django-nginx-secure.rule=Host(`stage.mood-diary.de`)"
      - "traefik.http.routers.django-nginx-secure.tls=true"
      - "traefik.http.routers.django-nginx-secure.tls.certresolver=dnsimple"
      - "traefik.http.routers.django-nginx-secure.tls.domains[0].main=mood-diary.de"
      - "traefik.http.routers.django-nginx-secure.tls.domains[0].sans=*.mood-diary.de"
      - "traefik.http.services.django-nginx.loadbalancer.server.port=8000"

  celery_consumer:
    restart: always
    image: ${APP_TEST_IMAGE}
    networks:
      - overlay
    env_file:
      - /home/docker/mood_diary/.env
    command: bash scripts/startup_celery_consumer.sh

  celery_beat:
    restart: always
    image: ${APP_TEST_IMAGE}
    networks:
      - overlay
    env_file:
      - /home/docker/mood_diary/.env
    command: bash scripts/startup_celery_scheduler.sh

networks:
  overlay:
  web:
    external: true
